.TH minibwa 1 "6 April 2026" "minibwa-0.0 (r210)" "Bioinformatics tools"
.SH NAME
.PP
minibwa - short/long-read alignment against a reference genome
.SH SYNOPSIS
* Indexing a genome with the libsais algorithm (OpenMP required for multi-threading):
.RS 4
minibwa index
.RB [ -t
.IR nThreads ]
.I ref.fa
.RE

* Indexing a genome in low memory with the BWT-SW algorithm:
.RS 4
minibwa index
.B -l
.I ref.fa
.RE

* Aligning short paired-end reads to an indexed genome and outputting SAM:
.RS 4
minibwa map
.B -a
.RB [ -t
.IR nThreads ]
.I ref.fa
.I read1.fq.gz
.I read2.fq.gz
>
.I output.sam
.RE

* Aligning long reads to an indexed genome and outputting PAF:
.RS 4
minibwa map
.B -x lr
.RB [ -t
.IR nThreads ]
.I ref.fa
.I read.fq.gz
>
.I output.sam
.RE

.SH DESCRIPTION
Minibwa aligns short and long reads against a reference genome. It is the
successor of bwa-mem for short-read alignment with a different algorithm.
Minibwa is 3-4 times as fast as the original bwa-mem and twice as fast as
bwa-mem2 at comparable accuracy. While minibwa works with accurate long reads,
it does not aim to replace minimap2. 

Minibwa is named after bwa-mem and minimap2 and is based on the source code of
both projects: it indexes the genome with Burrow-Wheeler Transform (BWT), finds
variable-length seeds as nested SuperMaximal Exact Matches (SMEMs) like
bwa-mem, and performs chaining and SIMD-based nucleotide alignment with the
minimap2 algorithm. Minibwa speeds up bwa-mem2 further with effective prefetch
for seeding, additional heuristics to skip unnecessary mate rescue and reduced
effort in highly repetitive regions where reads would often be wrongly mapped
anyway.

.SH THE INDEX COMMAND
.SS Summary
.B minibwa index
.RB [ -p
.IR prefix ]
.RB [ -l ]
.RB [ -n
.IR nThreads ]
.I ref.fa

Index a genome in the FASTA format. Generate
.IR prefix .l2b
for the genome sequence and
.IR prefix .mbw
for the FM-index.

.SS Options
.TP 10
.BI -p \ STR
Prefix of the output index [same as
.IR ref.fa ]
.TP
.B -l
Use the old low-memory algorithm for BWT construction. Minibwa uses the libsais
algorithm by default which uses over 50 GB for a human genome.
.TP
.BI -t \ INT
Number of threads for the libsais algorithm [1]. Minibwa needs to be compiled
with OpenMP to enable this option.

.SH THE MAP COMMAND
.SS Summary
.B minibwa map
.RB [ -a ]
.RB [ -x
.IR preset ]
.RB [ -t
.IR nThreads ]
.I ref.fa
.I read.fq.gz
.RI [ read2.fq.gz ]

.SS Mapping options
.TP 10
.B -x \ STR
Preset:
.B sr
for short reads or
.B lr
for long reads
.RB [ sr ]
